# Generated by Django 3.2.6 on 2021-08-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simparameters',
            name='compressor_efficiency',
            field=models.DecimalField(decimal_places=2, default=0.85, max_digits=2),
        ),
        migrations.AlterField(
            model_name='simparameters',
            name='dh_heat_demand_in_watts',
            field=models.IntegerField(default=4000000),
        ),
        migrations.AlterField(
            model_name='simparameters',
            name='dh_supply_temp',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='simparameters',
            name='district_heating_pump_efficiency',
            field=models.DecimalField(decimal_places=2, default=0.75, max_digits=2),
        ),
        migrations.AlterField(
            model_name='simparameters',
            name='evaporator_pump_efficiency',
            field=models.DecimalField(decimal_places=2, default=0.85, max_digits=2),
        ),
        migrations.AlterField(
            model_name='simparameters',
            name='lower_terminal_temperature_difference_evaporator',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='simparameters',
            name='pressure_in_bar_dh',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='simparameters',
            name='pressure_in_bar_waste_heat_fluid',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='simparameters',
            name='return_pressure_from_heat_pump',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='simparameters',
            name='return_temperature_from_heat_pump',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='simparameters',
            name='temp_district_heat_return',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='simparameters',
            name='upper_terminal_temperature_difference_condenser',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='simparameters',
            name='wasted_heat_design_temperature',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='simparameters',
            name='water_pump_efficiency',
            field=models.DecimalField(decimal_places=2, default=0.75, max_digits=2),
        ),
    ]
