# Generated by Django 3.2.6 on 2021-08-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations_app', '0002_auto_20210815_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simparameters',
            name='compressor_efficiency',
            field=models.FloatField(default=0.85),
        ),
        migrations.AlterField(
            model_name='simparameters',
            name='district_heating_pump_efficiency',
            field=models.FloatField(default=0.75),
        ),
        migrations.AlterField(
            model_name='simparameters',
            name='evaporator_pump_efficiency',
            field=models.FloatField(default=0.85),
        ),
        migrations.AlterField(
            model_name='simparameters',
            name='return_temperature_from_heat_pump',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='simparameters',
            name='wasted_heat_design_temperature',
            field=models.IntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='simparameters',
            name='water_pump_efficiency',
            field=models.FloatField(default=0.75),
        ),
    ]
